---
- name: Update apt
  become: true
  apt: update_cache=yes cache_valid_time=3600 force=yes

- name: Specify MySQL root password before installing
  become: true
  debconf:
    name: "mysql-server"
    question: "mysql-server/{{ item }}"
    value: "{{ mysql_root_pass| quote }}"
    vtype: "password"
  with_items:
    - root_password
    - root_password_again

- name: Install packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - git
    - git
    - libapache2-mod-php
    - mysql-client
    - mysql-server
    - php-cli
    - php-json-schema
    - php-mbstring
    - php7.2
    - php7.2-bcmath
    - php7.2-curl
    - php7.2-gd
    - php7.2-intl
    - php7.2-json
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-opcache
    - php7.2-readline
    - php7.2-sqlite3
    - php7.2-xml
    - php7.2-xmlrpc
    - php7.2-zip
    - python-mysqldb
    - unzip

- shell: hostname
  register: current_hostname

- name: Update root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create databases
  mysql_db:
    name: "{{ arc_mysql_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"

- name: Ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: Create users
  mysql_user:
    name: "{{ arc_mysql_user }}"
    password: "{{ arc_mysql_pass }}"
    priv: "{{ arc_mysql_name }}.*:ALL"
    state: present 
    login_user: root
    login_password: "{{ mysql_root_pass }}"

- name: Ensure target dir
  become: true
  file:
    path: /var/www/arc
    state: directory
    mode: 0775
    owner: "{{ ansible_ssh_user }}"
