version: '3.5'
services:
  # 192.168.21.97:5000/arcvouchers/service:prod
  # 192.168.21.97:5000/arcvouchers/market:prod

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=arcv
      - MYSQL_USER=arcvuser
      - MYSQL_PASSWORD=arcvpassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - service_public:/opt/project/public:ro
      - market_public:/opt/market/public:ro
    restart: unless-stopped
    depends_on:
      - service
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  service:
    image: 192.168.21.97:5000/arcvouchers/service:prod
    environment:
      - APP_URL=http://arcv-service.test:8080
      - ARC_MARKET_URL=http://arcv-market.test:8081
      - ARC_STORE_DOMAIN=arcv-store.test
      - DB_CONNECTION=mysql
      - DB_HOST=sqldb
      - DB_PORT=3306
      - DB_DATABASE=homestead
      - DB_USERNAME=arcvuser
      - DB_PASSWORD=arcvpassword
      - MAIL_HOST=mailer
      - MAIL_PORT=1025
    volumes:
      - storage:/opt/project/storage
      - service_public:/opt/project/public:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  market:
    image: 192.168.21.97:5000/arcvouchers/market:prod
    ports:
      - 8081:80
    environment:
      - API_BASE=http://arcv-service.test:8080/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "arcv-service.test:host-gateway"
      - "arcv-market.test:host-gateway"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_ADMIN_PORT:-1080}:1080"


volumes:
  service_public:
  market_public:
  storage:
  mysql:
