version: '3.5'
services:
  # 192.168.21.97:5000/arcvouchers/service:prod
  # 192.168.21.97:5000/arcvouchers/market:prod

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=arcv
      - MYSQL_USER=arcvuser
      - MYSQL_PASSWORD=arcvpassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  market:
    image: 192.168.21.97:5000/arcvouchers/market:prod
    volumes:
      - ./nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - service_public:/opt/project/public:ro
    depends_on:
      - service
    ports:
      - 443:443
      - 80:80
    environment:
      - API_BASE=https://arcv-service.test/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "arcv-service.test:host-gateway"
      - "arcv-store.test:host-gateway"
      - "arcv-market.test:host-gateway"
    restart: unless-stopped

  service:
    image: 192.168.21.97:5000/arcvouchers/service:prod
    environment:
      - APP_URL=http://arcv-service.test
      - ARC_MARKET_URL=http://arcv-market.test
      - ARC_STORE_DOMAIN=arcv-store.test
      - DB_CONNECTION=mysql
      - DB_HOST=sqldb
      - DB_PORT=3306
      - DB_DATABASE=arcv
      - DB_USERNAME=arcvuser
      - DB_PASSWORD=arcvpassword
      - LOG_CHANNEL=stderr
      - MAIL_HOST=mailer
      - MAIL_PORT=1025
      - SESSION_SECURE_COOKIE=false
    volumes:
      - storage:/opt/project/storage
      - service_public:/opt/project/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "arcv-service.test:host-gateway"
      - "arcv-store.test:host-gateway"
      - "arcv-market.test:host-gateway"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_ADMIN_PORT:-2080}:1080"


volumes:
  service_public:
  storage:
  mysql:
