version: '2.1'
services:

    sqldb:
        image: mysql:5.7
        environment:
            MYSQL_USER: lamp
            MYSQL_PASSWORD: lamp
            MYSQL_DATABASE: lamp
            MYSQL_ROOT_PASSWORD: notSecureChangeMe
        volumes:
              #- mysql:/var/lib/mysql
            - ./initdb.d:/docker-entrypoint-initdb.d
        restart: always
        ports:
          - "${SQLDB_PORT:-3336}:3306"
        healthcheck:
            test: ["CMD", "mysql" ,"-u", "lamp", "-plamp", "-h", "localhost", "lamp", "-e", "'desc user;'"]
            interval: 20s
            retries: 10

    testdb:
        image: mysql:5.7
        environment:
            MYSQL_USER: testing
            MYSQL_PASSWORD: testing
            MYSQL_DATABASE: testing
            MYSQL_ROOT_PASSWORD: notSecureChangeMe
        tmpfs: /var/lib/mysql
        restart: always
        ports:
          - "${TESTDB_PORT:-3337}:3306"
        healthcheck:
            test: ["CMD", "mysql" ,"-u", "testing", "-ptesting", "-h", "localhost", "testing", "-e", "'desc user;'"]
            interval: 20s
            retries: 10

    mailer:
        image: schickling/mailcatcher
        ports:
            - "${MAILER_SMTP_PORT:-1025}:1025"
            - "${MAILER_ADMIN_PORT:-1080}:1080"

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "${PHPMYADMIN_PORT:-8800}:80"
        environment:
            PMA_HOST: sqldb
            PMA_USER: lamp
            PMA_PASSWORD: lamp

volumes:
    mysql:
