---
- name: Playbook to release Vue (Market)
  hosts: myservers
  become: yes
  tasks:
    - name: Ensure release dir
      file:
        path: /var/www/ARCVMarket/releases/
        state: directory

    - name: Get release
      ansible.builtin.get_url:
        url: https://github.com/neontribe/ARCVMarket/archive/refs/tags/{{ tag }}.tar.gz
        dest: /var/tmp/release.tgz
        mode: '0440'

    - name: Unpack release
      unarchive:
        src: /var/tmp/release.tgz
        dest: /var/tmp
        remote_src: yes

    - name: Set up git versions for webpack to read
      shell: |
        git init
        git config --global user.email 'ansible@neontribe.org'
        git config --global user.name "Ansible Bot"
        git commit --allow-empty --no-verify -m "chore: deploy {{ tag }}"
      args:
        chdir: /var/tmp/ARCVMarket-{{ tag }}

    - name: Yarn install
      shell: yarn
      args:
        executable: /bin/bash
        chdir: /var/tmp/ARCVMarket-{{ tag }}

    - name: Yarn build
      shell: yarn build
      args:
        executable: /bin/bash
        chdir: /var/tmp/ARCVMarket-{{ tag }}

    # This for some reason doesn't work
#      yarn:
#        name: build
#        production: true
#        path: /var/tmp/ARCVMarket-{{ tag }}

    - name: Copy built files
      copy:
        src: /var/tmp/ARCVMarket-{{ tag }}/dist/
        dest: /var/www/ARCVMarket/releases/ARCVMarket-{{ tag }}
        remote_src: yes

    - name: Check if the .htaccess file exists
      stat:
        path: files/htaccess
      register: ht_access_file_status

    - name: Copy the .htaccess file if it does not exist
      copy:
        src: /path/to/source/file
        dest: /path/to/destination/file
      when: not ht_access_file_status.stat.exists

    - name: Link in htaccess
      file:
        state: link
        src: /var/www/ARCVMarket/htaccess
        dest: /var/www/ARCVMarket/releases/ARCVMarket-{{ tag }}/.htaccess

    - name: Ensure ownership
      file:
        dest: /var/www/ARCVMarket/releases/ARCVMarket-{{ tag }}
        owner: "{{ webuser }}"
        group: "{{ webuser }}"
        mode: u=rwX,g=rX,o=rX
        recurse: yes

    - name: Release it by updating public_html symlink
      file:
        state: link
        src: /var/www/ARCVMarket/releases/ARCVMarket-{{ tag }}
        dest: /var/www/ARCVMarket/public_html

