---
- name: Install http -> https redirect
  template:
    src: http-redirect.conf.j2
    dest: /etc/apache2/sites-available/http-redirect.conf
  when: protocol is not defined or protocol != "http"

- name: Install voucher-admin vhost (HTTPS)
  template:
    src: https.voucher-admin.alexandrarose.org.uk.conf.j2
    dest: /etc/apache2/sites-available/voucher-admin.alexandrarose.org.uk.conf
  when: protocol is not defined or protocol != "http"

- name: Install voucher vhost (HTTPS)
  template:
    src: https.voucher.alexandrarose.org.uk.conf.j2
    dest: /etc/apache2/sites-available/voucher.alexandrarose.org.uk.conf
  when: protocol is not defined or protocol != "http"

- name: Install voucher-store vhost (HTTPS)
  template:
    src: https.voucher-store.alexandrarose.org.uk.conf.j2
    dest: /etc/apache2/sites-available/voucher-store.alexandrarose.org.uk.conf
  when: protocol is not defined or protocol != "http"

- name: Install voucher-mail vhost (HTTPS)
  template:
    src: https.voucher-mail.alexandrarose.org.uk.conf.j2
    dest: /etc/apache2/sites-available/voucher-mail.alexandrarose.org.uk.conf
  when:
    - arc_source == "arc_live"
    - protocol is not defined or protocol != "http"

- name: Install voucher-admin vhost (HTTP)
  template:
    src: http.voucher-admin.alexandrarose.org.uk.conf.j2
    dest: /etc/apache2/sites-available/voucher-admin.alexandrarose.org.uk.conf
  when: protocol is defined and protocol == "http"

- name: Install voucher vhost (HTTP)
  template:
    src: http.voucher.alexandrarose.org.uk.conf.j2
    dest: /etc/apache2/sites-available/voucher.alexandrarose.org.uk.conf
  when: protocol is defined and protocol == "http"

- name: Install voucher-store vhost (HTTP)
  template:
    src: http.voucher-store.alexandrarose.org.uk.conf.j2
    dest: /etc/apache2/sites-available/voucher-store.alexandrarose.org.uk.conf
  when: protocol is defined and protocol == "http"

- name: Install voucher-mail vhost (HTTP)
  template:
    src: http.voucher-mail.alexandrarose.org.uk.conf.j2
    dest: /etc/apache2/sites-available/voucher-mail.alexandrarose.org.uk.conf
  when:
    - arc_source == "arc_live"
    - protocol is defined and protocol == "http"

- name: Enable mod_rewrite mod_ssl
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - ssl

- name: Disable default https 
  command: a2dissite default-ssl

- name: Disable default http 
  command: a2dissite 000-default
  when: protocol is defined and protocol == "http"

- name: Enable the arc vhost sites
  command: a2ensite {{ item }}
  with_items:
    - voucher-admin.alexandrarose.org.uk
    - voucher-mail.alexandrarose.org.uk
    - voucher-store.alexandrarose.org.uk
    - voucher.alexandrarose.org.uk

- name: Enable apache and mysql
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - apache2
    - mysql
