- name: Playbook to dump SQL db (Store/Service)
  hosts: myservers
  become: yes

  tasks:

    - name: Ensure sql dump dir
      file:
        path: /var/www/ARCVService/db-dumps
        state: directory

    - name: Get current release
      stat:
        path: /var/www/ARCVService/current_release
      register: sym

    - name: Set current release name as fact
      set_fact:
        current_release: "{{ sym.stat.lnk_source | basename }}"

    - name: SQL dump file name as fact
      set_fact:
        dump_file: "{{ current_release }}_{{ ansible_date_time.iso8601 }}.sql"

    - name: Dump DB
      shell: |
        mysqldump -u {{ db_user_name }} \
          -p"{{ db_user_password }}" \
          -h127.0.0.1 \
          {{ db_name }} \
          --quick \
          --lock-tables=false > "/var/www/ARCVService/db-dumps/{{ dump_file }}"

    - name: Gzip the dump file
      archive:
        path: "/var/www/ARCVService/db-dumps/{{ dump_file }}"
        remove: true

#    - name: Get the dump
#      fetch:
#        src: "/var/www/ARCVService/db-dumps/{{ dump_file }}"
#        dest: dbdumps
