
#- import_playbook: dump-db.yml

- name: Playbook to release laravel (Store/Service)
  hosts: myservers
  become: yes

  tasks:

    - name: Clear storage directory
      file:
        state: absent
        path: /var/www/ARCVService/releases/ARCVService-{{ tag }}/storage
      become: yes

    - name: Link in .env
      file:
        state: link
        src: /var/www/ARCVService/service_env
        dest: /var/www/ARCVService/releases/ARCVService-{{ tag }}/.env
      become: yes

    - name: Link in storage
      file:
        state: link
        src: /var/www/ARCVService/storage
        dest: /var/www/ARCVService/releases/ARCVService-{{ tag }}/storage
      become: yes

    - name: Generate assets
      shell: yarn production
      args:
        executable: /bin/bash
        chdir: /var/www/ARCVService/releases/ARCVService-{{ tag }}
      become: yes

    - name: Link current_release
      file:
        state: link
        force: true
        src: /var/www/ARCVService/releases/ARCVService-{{ tag }}
        dest: /var/www/ARCVService/current_release
      become: yes

    - name: Link public_html
      file:
        state: link
        force: true
        src: /var/www/ARCVService/releases/ARCVService-{{ tag }}/public
        dest: /var/www/ARCVService/public_html
      become: yes

    - name: Run migrations
      shell: php artisan migrate
      args:
        executable: /bin/bash
        chdir: /var/www/ARCVService/current_release
      become: yes

    - name: Cache clear, Config clear, Optimise
      shell: php artisan {{ item }}
      args:
        executable: /bin/bash
        chdir: /var/www/ARCVService/current_release
      with_items:
        # - cache:clear
        # - config:clear
        # - optimize:clear
        # - view:clear
        - clear-compiled
      become: yes

    - name: Ensure ownership (web)
      file:
        dest: /var/www/ARCVService/{{ item }}
        owner: "{{ webuser }}"
        group: "{{ webuser }}"
        mode: u=rwX,g=rX,o=rX
        recurse: yes
      become: yes
      with_items:
        - storage
        - current_release/bootstrap
        - /var/www/ARCVService/releases/ARCVService-{{ tag }}/bootstrap
        - /var/www/ARCVService/releases/ARCVService-{{ tag }}/storage
